services:
  - type: web
    name: ithouse
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
    startCommand: gunicorn base.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: base.settings
      - key: SECRET_KEY
        value: django-insecure-...
      - key: DEBUG
        value: 'False'
