# Generated by Django 5.0.4 on 2025-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('narhi', models.IntegerField()),
                ('tavsifi', models.CharField(max_length=250)),
            ],
        ),
    ]
