# Generated by Django 5.0.4 on 2025-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='karta_tolovi',
            field=models.IntegerField(null=True),
        ),
    ]
