# Generated by Django 5.0.4 on 2025-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_tovar_karta_tolovi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='super_narh',
            field=models.BooleanField(default=False),
        ),
    ]
