# Generated by Django 5.0.4 on 2025-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_tovar_super_narh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='orginal',
            field=models.BooleanField(default=False),
        ),
    ]
