# Generated by Django 5.0.4 on 2025-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_tovar_orginal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qoshimcha_Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media')),
                ('asosiy_narh', models.IntegerField()),
                ('malumot_uchun', models.CharField(max_length=250)),
            ],
        ),
    ]
