# Generated by Django 5.0.4 on 2025-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_qoshimcha_tovar'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoshimcha_tovar',
            name='is_arginal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qoshimcha_tovar',
            name='is_karat_narh',
            field=models.IntegerField(null=True),
        ),
    ]
