# Generated by Django 5.0.4 on 2025-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_qoshimcha_tovar_is_arginal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='rasm_main',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
