# Generated by Django 5.0.4 on 2025-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_tovar_rasm_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='rasm1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm10',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm2',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm3',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm4',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm5',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm6',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm7',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm8',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rasm9',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
