# Generated by Django 5.0.4 on 2025-10-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_tovar_rasm1_tovar_rasm10_tovar_rasm2_tovar_rasm3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm1',
            new_name='rasm_besh',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm10',
            new_name='rasm_ikki',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm2',
            new_name='rasm_olti',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm3',
            new_name='rasm_on',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm4',
            new_name='rasm_sakiz',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm5',
            new_name='rasm_toqiz',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm6',
            new_name='rasm_tort',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm7',
            new_name='rasm_uch',
        ),
        migrations.RenameField(
            model_name='tovar',
            old_name='rasm8',
            new_name='rasm_yeti',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='rasm9',
        ),
    ]
