# Generated by Django 5.0.4 on 2025-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_rename_rasm1_tovar_rasm_besh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='rasm_bir',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
